# To get the data into the production datastore you'll need to run the bulkloader. 
# First, copy words-full.txt to words-full.csv, adding this header line:
# word,rhymeId,rhymeCount,popularity

# Then, from an up-to-date appengine SDK
# appcfg.py upload_data --config_file=C:\path\to\config.yml --filename=C:\path\to\words-full.csv --url=http://jonbonrobot.appspot.com/remote_api --kind=Word

python_preamble:
- import: base64
- import: re
- import: google.appengine.ext.bulkload.transform
- import: google.appengine.ext.bulkload.bulkloader_wizard
- import: google.appengine.ext.db
- import: google.appengine.api.datastore
- import: google.appengine.api.users
 
transformers:
 
- kind: Word
  connector: csv
 
  property_map:
 
    - property: word
      external_name: word
 
    - property: rhymeId
      external_name: rhymeId
      import_transform: transform.none_if_empty(int)
      
    - property: rhymeCount
      external_name: rhymeCount
      import_transform: transform.none_if_empty(int)
      
    - property: popularity
      external_name: popularity
      import_transform: transform.none_if_empty(int)