package com.songscoreapp.server.generator;

import java.io.BufferedReader;
import java.io.IOException;
import java.io.InputStreamReader;
import java.net.URL;
import java.net.URLConnection;

public class RhymeScraper {


    public static void main(String[] args) {
        try {
            for(String word : wordsToQuery) {
                String java = scrape(word);
                if(java.length() > 0) {
                    System.out.println(scrape(word));
                }
            }
        } catch(Exception e) {
            e.printStackTrace();
        }
    }


    /**
     *
     * Bug in RhymeZone: we have to ask for phrases then throw out everything with a space.
     * Without phrases RhymeZone doesn't understand that your rhymes with for
     *
     * @param word
     * @return
     * @throws IOException
     */
    public static String scrape(String word) throws IOException {
        StringBuffer sb = new StringBuffer("");

        String URL = "http://www.rhymezone.com/r/rhyme.cgi?Word=" + word + "&typeofrhyme=perfect&org1=syl&org2=l&org3=y";
        URL site = new URL(URL);
        URLConnection connection = site.openConnection();

        BufferedReader in = new BufferedReader(new InputStreamReader(connection.getInputStream()));
        String inputLine;

        boolean listening = false;
        while ((inputLine = in.readLine()) != null) {
            //System.out.println(inputLine);
            if(inputLine.contains("words ending with")) {
                listening = false;
            }
            if(listening || inputLine.contains("Words and phrases that rhyme with")) {
                listening = true;
                if(inputLine.contains("A HREF")) {
                    inputLine = inputLine.replace("<b>", "");
                    inputLine = inputLine.replace("</b>", "");
                    inputLine = inputLine.substring(inputLine.indexOf('>') + 1);
                    inputLine = inputLine.substring(0, inputLine.indexOf('<'));
                    if(!inputLine.contains("&nbsp;")) {
                        sb.append(inputLine + ",");
                    }
                }
            }
        }
        String returnString = "";
        if(sb.length() > 0) {
            returnString = sb.toString().substring(0, sb.length() - 1);
        } else {
            return "";
        }
        return word + "," + returnString;
    }

    static String[] wordsToQuery = {"nailing"};
    /*
    "ha",
    "blab",
    "back",
    "ace",
    "batch",
    "act",
    "add",
    "aid",
    "badge",
    "adds",
    "chaff",
    "aft",
    "age",
    "staff",
    "rage",
    "staffed",
    "waft",
    "rag",
    "assuage",
    "scarf",
    "paragraphed",
    "ale",
    "mall",
    "aim",
    "bane",
    "paint",
    "lair",
    "glared",
    "days",
    "bait",
    "wraith",
    "ache",
    "enthralled",
    "talk",
    "gawk",
    "arm",
    "psalm",
    "alms",
    "FALSE",
    "fault",
    "salt",
    "halve",
    "valve",
    "ax",
    "am",
    "scamp",
    "ban",
    "chance",
    "blanch",
    "and",
    "romance",
    "carte-blanche",
    "bang",
    "change",
    "bank",
    "ant",
    "cap",
    "nape",
    "traipse",
    "apse",
    "apt",
    "star",
    "hussar",
    "barb",
    "arch",
    "bard",
    "barge",
    "arc",
    "snarl",
    "arm",
    "barn",
    "carp",
    "bars",
    "marsh",
    "art",
    "hearth",
    "carve",
    "has",
    "ash",
    "wash",
    "ask",
    "chasm",
    "grasp",
    "ass",
    "coup de grace",
    "blast",
    "paced",
    "at",
    "bath",
    "orb",
    "fraud",
    "taught",
    "haunch",
    "daunt",
    "awes",
    "exhaust",
    "slave",
    "awe",
    "prawn",
    "day",
    "be",
    "cease",
    "beach",
    "agreed",
    "chef",
    "league",
    "leak",
    "deal",
    "field",
    "elm",
    "health",
    "beam",
    "dreamt",
    "",
    "sheen",
    "fiend",
    "cheap",
    "rear",
    "church",
    "bird",
    "beard",
    "pearl",
    "learn",
    "earth",
    "bees",
    "beast",
    "beat",
    "guarantees",
    "policed",
    "meat",
    "teeth",
    "breathe",
    "retrieve",
    "web",
    "henpeck",
    "wrecked",
    "bed",
    "edge",
    "grief",
    "cleft",
    "leg",
    "bell",
    "belled",
    "help",
    "belt",
    "shelve",
    "gem",
    "den",
    "when",
    "cleanse",
    "hence",
    "bench",
    "bend",
    "scent",
    "step",
    "crept",
    "blur",
    "burrs",
    "curb",
    "surf",
    "verge",
    "kirk",
    "firm",
    "blurt",
    "curve",
    "bless",
    "flesh",
    "desk",
    "best",
    "bet",
    "etch",
    "cue",
    "who",
    "vex",
    "fez",
    "bib",
    "bribe",
    "brick",
    "rice",
    "bricked",
    "bid",
    "bide",
    "bridge",
    "amidst",
    "liege",
    "fierce",
    "cliff",
    "wife",
    "thrift",
    "swig",
    "tyke",
    "bill",
    "build",
    "wild",
    "aisle",
    "bilk",
    "built",
    "filth",
    "brim",
    "spike",
    "chime",
    "sometimes",
    "crimp",
    "bin",
    "since",
    "cinch",
    "instinct",
    "sinned",
    "bind",
    "wine",
    "wing",
    "fringe",
    "blink",
    "sink",
    "print",
    "sphinx",
    "chip",
    "tripe",
    "eclipse",
    "briar",
    "burst",
    "biz",
    "bliss",
    "comprise",
    "dish",
    "bisque",
    "prism",
    "fist",
    "fit",
    "itch",
    "bite",
    "myth",
    "blithe",
    "dive",
    "give",
    "nix",
    "beau",
    "broach",
    "bode",
    "toad",
    "loaf",
    "woke",
    "hoax",
    "toll",
    "roam",
    "bone",
    "lower",
    "ford",
    "boast",
    "bloat",
    "both",
    "bob",
    "globe",
    "block",
    "blocked",
    "cod",
    "lodge",
    "dislodge",
    "off",
    "oft",
    "bog",
    "rogue",
    "choice",
    "avoid",
    "employed",
    "toll",
    "turmoil",
    "loin",
    "noise",
    "hoist",
    "adroit",
    "doll",
    "bold",
    "moist",
    "exploit",
    "told",
    "folk",
    "bolt",
    "solve",
    "bomb",
    "con",
    "hold",
    "nonce",
    "pond",
    "thong",
    "font",
    "don't",
    "bronze",
    "Oo (see Ew)",
    "could",
    "dude",
    "blued",
    "roof",
    "book",
    "mule",
    "rule",
    "consume",
    "boon",
    "dupe",
    "poop",
    "you're",
    "boor",
    "deuce",
    "dues",
    "roost",
    "foot",
    "lute",
    "tooth",
    "soothe",
    "prove",
    "chop",
    "cope",
    "drawer",
    "course",
    "porch",
    "chord",
    "orb",
    "gorge",
    "cork",
    "form",
    "born",
    "warp",
    "horse",
    "sport",
    "north",
    "engross",
    "hose",
    "boss",
    "frost",
    "dot",
    "notch",
    "broth",
    "couch",
    "crowd",
    "bounce",
    "bound",
    "count",
    "flower",
    "morn",
    "dowse",
    "espouse",
    "bout",
    "south",
    "love",
    "vow",
    "owl",
    "brown",
    "pox",
    "boy",
    "drub",
    "cube",
    "clutch",
    "luck",
    "conduct",
    "blood",
    "judge",
    "gruff",
    "shrug",
    "duke",
    "bull",
    "bulge",
    "bulk",
    "impulse",
    "cult",
    "chum",
    "bump",
    "ton",
    "dunce",
    "brunch",
    "fund",
    "rung",
    "lunge",
    "bunk",
    "runt",
    "up",
    "interrupt",
    "world",
    "bus",
    "bush",
    "blush",
    "dusk",
    "crust",
    "but",
    "crux",
    "jut",
    "tusk",
    "buy"};
*/
}
